### ISSUE TITLE
Test runner causing API errors on document-parser

### ISSUE THREAD

**Issue by betamax** [rm3l/dev-feed#74]
Hello! I am Max from [Lateral](https://lateral.io). You appear to be using our [document-parser](https://lateral.io/docs/article-extractor) api in your code [here](https://github.com/rm3l/dev-feed/blob/4109d3d29dd7ba69f7ab2c8509936c9a1c299e67/backend/src/main/kotlin/org/rm3l/devfeed/crawlers/ArticleExtractor.kt) and [here](https://github.com/rm3l/dev-feed/blob/4109d3d29dd7ba69f7ab2c8509936c9a1c299e67/backend/src/main/kotlin/org/rm3l/devfeed/crawlers/DevFeedFetcherService.kt). This is totally fine, however we are getting an unusual amount of errors from the document-parser every week - about 94,000:

![image](https://user-images.githubusercontent.com/246674/86269625-4f831500-bbca-11ea-9f94-350c69396279.png)

This has been going on for months now and was a bit of a mystery to us, because the requests don't use a Subscription-Key which would indicate to us who is making the requests. Today my colleague told me that the referrer was using a Kotlin HTTP client, so I decided to search on GitHub for the API name and lo and behold, there was one repository written in Kotlin that used our API!

I have a suspicion, that maybe your test runner is making live requests to our API using no Subscription-Key header. Would you be able to possibly confirm whether this is happening, and if so stop making these requests?

**Comment by rm3l** [comment]
@betamax Thanks for reporting this issue, which was indeed not intentional.
The goal was to make these calls optional by default , and active only if a Susbscription Key is provided.
This is however not the case in the code.
I'll fix that as soon as possible.
Thanks for your understanding, and sorry for the inconvenience.

**Comment by rm3l** [comment]
Hi @betamax !

The tests and configuration should be fixed. Could you please confirm on your side you are no longer receiving requests with no subscription key?
Thanks.

**Comment by betamax** [comment]
Hi @rm3l,

I can confirm the issue is resolved :) Thank you!

Max
